Repository GSG-G13/gym-react, pull requests merged in 2023-07, with the labels that each got.

#111 108 styling store page
  src/App.jsx
  src/components/categoriesList/index.jsx
  src/components/categoryCard/CategoryCard.jsx
  src/components/footer/Footer.jsx
  src/components/homeStore/HomeStore.jsx
  src/components/navbar/NavbarClient.jsx
  src/components/productCard/index.jsx
  src/components/productList/ProductList.jsx
  src/layout/Store.jsx
  src/layout/index.js
  src/pages/user/product/index.jsx
Labels: approved

#113 style signup
  src/components/button/Button.jsx
  src/components/inputfield/index.jsx
  src/components/signup/index.jsx
  src/components/signup/styledComps.jsx
  src/pages/user/signup/index.jsx
  src/pages/user/signup/styledComps.jsx
  src/utilize/icons.jsx
Labels: approved

#116 114 styling home dashboard page
  src/components/chart/index.jsx
  src/components/orderProductStatistic/OrderProductStatistic.jsx
  src/components/orderProductStatistic/ProductStatisticList.jsx
  src/components/ratingChart/index.jsx
  src/components/sideBar/SideBar.jsx
  src/components/statistic/index.jsx
  src/pages/admin/homeDashboard/index.jsx
  src/pages/admin/index.js
  src/pages/index.js
Labels: approved

#118 nav and product style
  src/components/categoriesList/index.jsx
  src/components/navbar/NavbarClient.jsx
  src/components/productCard/index.jsx
  src/components/productList/ProductList.jsx
Labels: approved

#122 109 styling class page
  src/App.jsx
  src/components/button/Button.jsx
  src/components/classInfo/index.jsx
  src/components/classesList/index.jsx
  src/pages/user/class/index.jsx
Labels: waiting-review

#121 fix profile page style
  src/components/profileNav/index.jsx
  src/pages/user/userProfile/index.jsx
Labels: waiting-review

#123 styling home page
  package-lock.json
  package.json
  src/components/headerClient/Header.jsx
  src/components/slider/index.jsx
  src/components/swiper/index.jsx
  src/components/table/index.jsx
  src/index.css
  src/pages/user/home/index.jsx
  src/routes/root.jsx
  src/styles/sliderHome.css
  src/styles/swiper.css
Labels: approved

#126 connection between front and back
  package-lock.json
  package.json
  vite.config.js
Labels: waiting-review

#137 sign up functionality
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/alert/Alert.jsx
  src/components/button/Button.jsx
  src/components/inputfield/index.jsx
  src/components/modal/index.jsx
  src/components/signup/index.jsx
  src/pages/user/signup/index.jsx
  src/validation/signupValidation.js
Labels: approved

#135 add sign in functionality
  package-lock.json
  package.json
  src/components/inputfield/index.jsx
  src/components/signinform/index.jsx
Labels: approved

#133 get all products
  src/components/productCard/index.jsx
  src/components/productList/ProductList.jsx
  src/layout/Store.jsx
Labels: approved

#134 132 get all categories
  src/App.jsx
  src/components/categoriesList/index.jsx
  src/components/categoryCard/CategoryCard.jsx
Labels: approved

#147 annnouncment add
  src/components/button/Button.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/components/formDashboard/GroupButtons.jsx
  src/components/formDashboard/InputForm.jsx
  src/components/newPopUpComp/index.jsx
  src/components/searchDashboard/Search.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/announcement/index.jsx
Labels: waiting-review

#141 139 get product by categories
  src/App.jsx
  src/components/categoriesList/index.jsx
  src/components/productList/ProductList.jsx
  src/pages/user/product/index.jsx
Labels: waiting-review

#149 get product table details dashboard
  src/components/table/index.jsx
  src/dummyData/productData.js
  src/pages/admin/productList/index.jsx
Labels: waiting-review

#146 get announcement
  src/components/announcement/Announcement.jsx
  src/components/announcement/AnnouncementList.jsx
Labels: waiting-review

#154 get announcments dashboard
  src/dummyData/announcementData.js
  src/pages/admin/announcement/index.jsx
Labels: waiting-review

#130 class functionality
  src/components/classInfo/index.jsx
  src/components/classesList/index.jsx
  src/pages/user/class/index.jsx
Labels: waiting-review

#158 add product dashboard
  src/components/formDashboard/FormDashBoard.jsx
  src/components/formDashboard/GroupButtons.jsx
  src/components/newPopUpComp/index.jsx
  src/components/searchDashboard/Search.jsx
  src/dummyData/productData.js
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/announcement/index.jsx
  src/pages/admin/productList/index.jsx
Labels: approved

#142 138 get product details
  src/App.jsx
  src/components/categoriesList/index.jsx
  src/components/productCard/index.jsx
  src/components/productDetailsCard/ProductDetails.jsx
Labels: waiting-review

#170 delete announcement
  src/pages/admin/announcement/index.jsx
Labels: waiting-review

#166 get orders dashboard
  src/App.jsx
  src/components/alert/Alert.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/dashbored-order/index.jsx
  src/pages/admin/index.js
  src/pages/index.js
Labels: waiting-review

#163 162 get subscription dashboard
  src/App.jsx
  src/components/alert/Alert.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/index.js
  src/pages/admin/subscription/index.jsx
  src/pages/index.js
Labels: waiting-review

#161 add subscription onclick join class button
  src/components/classInfo/index.jsx
Labels: waiting-review

#150 profile page functionality and change table
  src/App.jsx
  src/components/personalInfo/PersonalInfo.jsx
  src/components/profileNav/index.jsx
  src/pages/user/userProfile/classesTable.jsx
  src/pages/user/userProfile/dummyData.js
  src/pages/user/userProfile/index.jsx
  src/pages/user/userProfile/ordersTable.jsx
Labels: waiting-review

#173 167 user add order
  src/App.jsx
  src/components/alert/Alert.jsx
  src/components/announcement/Announcement.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/components/formDashboard/InputForm.jsx
  src/components/newPopUpComp/index.jsx
  src/components/productDetailsCard/ProductDetails.jsx
  src/components/searchDashboard/Search.jsx
  src/components/signinform/index.jsx
  src/components/table/index.jsx
  src/components/toastAlert/ToastAlert.jsx
  src/dummyData/index.js
  src/dummyData/productData.js
  src/layout/DashboardLayout.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/announcement/index.jsx
  src/pages/admin/productList/index.jsx
  src/pages/admin/user/index.jsx
Labels: approved

#177 138 add and get classes dashboard
  src/App.jsx
  src/components/alert/Alert.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/components/newPopUpComp/index.jsx
  src/components/searchDashboard/Search.jsx
  src/components/table/index.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/class/index.jsx
  src/pages/admin/user/index.jsx
Labels: waiting-review

#178 172 add static class main page
  src/App.jsx
  src/components/homeClass/index.jsx
  src/components/index.js
Labels: approved

#71 add message component and all messages container
  src/components/index.js
  src/components/message/index.jsx
  src/components/messageLists/index.jsx
Labels: waiting-review

#182 styling class page
  src/App.jsx
  src/components/button/Button.jsx
  src/components/classInfo/index.jsx
  src/components/classTable/ClassTable.jsx
  src/components/classesList/index.jsx
  src/layout/classLayout.jsx
  src/pages/user/class/index.jsx
Labels: waiting-review

#183 add eddit and delete functionality
  src/App.jsx
  src/components/deleteDataBtn/index.jsx
  src/components/dropDownList/index.jsx
  src/components/editData/index.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/dummyData/index.jsx
  src/dummyData/productData.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/announcement/index.jsx
  src/pages/admin/class/index.jsx
  src/pages/admin/dashbored-order/index.jsx
  src/pages/admin/subscription/index.jsx
Labels: approved

#168 145 user setting functionality
  src/App.jsx
  src/components/announcement/AnnouncementList.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/components/formDashboard/InputForm.jsx
  src/components/newPopUpComp/index.jsx
  src/components/signinform/index.jsx
  src/components/signup/index.jsx
  src/components/userSettingData/UserSettingData.jsx
  src/pages/user/userSetting/index.jsx
  src/validation/signupValidation.js
Labels: approved

#184 handle logout
  package-lock.json
  package.json
  src/components/formDashboard/InputForm.jsx
  src/components/navbar/NavbarClient.jsx
Labels: waiting-review

#189 styling profile page and logic
  src/components/classInfo/index.jsx
  src/components/formDashboard/InputForm.jsx
  src/components/profileNav/index.jsx
  src/components/userSettingData/UserSettingData.jsx
  src/pages/user/userProfile/classesTable.jsx
  src/pages/user/userProfile/index.jsx
  src/pages/user/userProfile/ordersTable.jsx
Labels: approved

#175 add chat and sockit clint package, still need to use chat component
  package-lock.json
  package.json
  src/App.jsx
  src/components/chat/index.jsx
  src/components/message/index.jsx
  src/components/messageLists/index.jsx
  src/components/orderProductStatistic/ProductStatisticList.jsx
  src/socket.js
  vite.config.js
Labels: approved

#191 add userdata to navbar and get the cookie
  src/components/navbar/NavbarClient.jsx
  src/components/swiper/index.jsx
  src/components/videoCom/index.jsx
  src/pages/user/userProfile/classesTable.jsx
Labels: approved

#193 et statistic section data home dashboard
  src/App.jsx
  src/components/navbarDashboard/index.jsx
  src/components/sideBar/SideBar.jsx
  src/components/statistic/index.jsx
  src/index.css
  src/layout/DashboardLayout.jsx
  src/pages/admin/LayOut/index.jsx
  src/pages/admin/homeDashboard/index.jsx
Labels: approved

#194 186 announcement styling
  src/components/announcement/Announcement.jsx
  src/components/announcement/AnnouncementList.jsx
Labels: approved

#198 get statistic order and rating chart
  src/components/orderProductStatistic/OrderProductStatistic.jsx
  src/components/orderProductStatistic/ProductStatisticList.jsx
  src/components/ratingChart/index.jsx
  src/layout/DashboardLayout.jsx
Labels: waiting-review

#196 styling store page
  src/App.jsx
  src/components/categoriesList/index.jsx
  src/components/categoryCard/CategoryCard.jsx
  src/components/classesList/index.jsx
  src/components/homeStore/HomeStore.jsx
  src/components/productDetailsCard/ProductDetails.jsx
  src/components/productList/ProductList.jsx
  src/index.css
  src/pages/user/product/index.jsx
Labels: approved

#200 Delete user info
  src/App.jsx
  src/components/userSettingData/UserSettingData.jsx
Labels: approved

#201 edit-functionality-dashboard
  src/components/dropDownList/index.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/dummyData/index.jsx
  src/dummyData/productData.jsx
  src/index.css
  src/pages/admin/class/index.jsx
  src/pages/admin/dashbored-order/index.jsx
  src/pages/admin/subscription/index.jsx
Labels: waiting-review

#206 styling product detailes page
  src/components/announcement/Announcement.jsx
  src/components/productDetailsCard/ProductDetails.jsx
  src/pages/user/productDetails/index.jsx
Labels: approved

#205 add, get, and delete comment
  src/App.jsx
  src/components/announcement/Announcement.jsx
  src/components/announcement/AnnouncementList.jsx
  src/components/userSettingData/UserSettingData.jsx
  src/index.css
Labels: approved

#207 style comments on announcement page
  package-lock.json
  package.json
  src/App.jsx
  src/components/announcement/Announcement.jsx
  src/components/announcement/AnnouncementList.jsx
  src/context/admin.jsx
  src/context/navigate.jsx
  src/hook/useAuth.jsx
  src/routes/root.jsx
  src/routes/router.jsx
Labels: waiting-review

#210 fix-dashboard-router-and-background-color
  src/App.jsx
  src/components/announcement/AnnouncementList.jsx
  src/components/chat/index.jsx
  src/components/sideBar/SideBar.jsx
  src/index.css
  src/pages/user/userProfile/index.jsx
  src/pages/user/userSetting/index.jsx
  src/routes/router.jsx
Labels: approved

#213 get trainers home page
  src/App.jsx
  src/components/signinform/index.jsx
  src/components/swiper/index.jsx
  src/context/navigate.jsx
  src/layout/DashboardLayout.jsx
  src/pages/user/home/index.jsx
  src/routes/root.jsx
Labels: approved

#214 211 logout admin
  src/components/navbarDashboard/index.jsx
Labels: approved

#217 user reset his account password
  src/components/passwordFrom/index.jsx
  src/components/productDetailsCard/style.js
  src/components/signinform/index.jsx
  src/pages/user/signin/index.jsx
Labels: approved

#219 admin profile and edit data
  src/components/navbarDashboard/index.jsx
  src/pages/admin/index.js
  src/pages/admin/profile/index.jsx
  src/pages/index.js
  src/routes/router.jsx
Labels: approved

#222 221 edit class page and show user in chat and add check token
  src/App.jsx
  src/assets/class-removebg-preview.png
  src/assets/class2-removebg-preview.png
  src/assets/class3-removebg-preview.png
  src/assets/class4-removebg-preview.png
  src/assets/singupimage.svg
  src/assets/undraw_newsletter_re_wrob.svg
  src/assets/undraw_social_interaction_re_dyjh.svg
  src/assets/undraw_team_page_re_cffb.svg
  src/assets/undraw_time_management_re_tk5w.svg
  src/components/chat/index.jsx
  src/components/classInfo/index.jsx
  src/components/classTable/ClassTable.jsx
  src/components/classesList/index.jsx
  src/components/homeClass/index.jsx
  src/components/message/index.jsx
  src/components/messageLists/index.jsx
  src/components/navbar/NavbarClient.jsx
  src/components/navbarDashboard/index.jsx
  src/components/productDetailsCard/ProductDetails.jsx
  src/components/signinform/index.jsx
  src/components/userSettingData/UserSettingData.jsx
  src/components/videoCom/index.jsx
  src/context/admin.jsx
  src/context/authContex.js
  src/context/authorization.jsx
  src/dummyData/index.js
  src/dummyData/productData.js
  src/hook/useAuth.jsx
  src/hook/useLocalStorage.jsx
  src/hook/useUser.jsx
  src/index.css
  src/layout/classLayout.jsx
  src/pages/user/class/index.jsx
  src/pages/user/productDetails/index.jsx
  src/pages/user/userProfile/index.jsx
  src/routes/router.jsx
Labels: waiting-review

#225 add and get and update and delete functionailty dashboard
  src/context/navigate.jsx
  src/dashboardComponents/button/editButton.jsx
  src/dashboardComponents/form/Editform.jsx
  src/dashboardComponents/form/addForm.jsx
  src/dashboardComponents/navbar/index.jsx
  src/dashboardComponents/table/index.jsx
  src/pages/admins/announcements/index.jsx
  src/pages/admins/orders/index.jsx
  src/pages/admins/users/index.jsx
Labels: waiting-review

#228 226 dashboard home functionality
  .vscode/settings.json
  src/dashboardComponents/card/index.jsx
  src/dashboardComponents/orders/Orders.jsx
  src/dashboardComponents/orders/index.jsx
  src/dashboardComponents/rating/index.jsx
  src/dashboardComponents/table/index.jsx
  src/pages/admins/announcements/index.jsx
  src/pages/admins/home/index.jsx
  src/pages/admins/profile/index.jsx
  src/pages/admins/users/index.jsx
Labels: waiting-review

#231 check user while ordering and subscription and user delete subs an or…
  src/components/announcement/Announcement.jsx
  src/components/classInfo/index.jsx
  src/components/productDetailsCard/ProductDetails.jsx
  src/pages/user/userProfile/classesTable.jsx
  src/pages/user/userProfile/index.jsx
  src/pages/user/userProfile/ordersTable.jsx
Labels: waiting-review

#232 fix announcement page
  src/components/announcement/Announcement.jsx
  src/pages/admins/orders/index.jsx
Labels: waiting-review

#234 style rest password,get class,trainer,subscription count for class page
  src/components/classInfo/index.jsx
  src/components/homeClass/index.jsx
  src/components/passwordFrom/index.jsx
  src/components/userSettingData/UserSettingData.jsx
  src/dashboardComponents/card/index.jsx
  src/pages/user/signin/index.jsx
Labels: waiting-review

#235 fix edit functionality
  .vscode/settings.json
  src/components/classesList/index.jsx
  src/components/formDashboard/FormDashBoard.jsx
  src/components/formDashboard/InputForm.jsx
  src/components/homeClass/index.jsx
  src/components/newPopUpComp/index.jsx
  src/components/userSettingData/UserSettingData.jsx
  src/dashboardComponents/card/index.jsx
  src/dashboardComponents/form/Editform.jsx
  src/dashboardComponents/orders/index.jsx
  src/pages/admins/Classes/index.jsx
  src/pages/admins/announcements/index.jsx
  src/pages/admins/home/index.jsx
  src/pages/admins/products/index.jsx
  src/pages/admins/users/index.jsx
  src/utilize/Theme.jsx
Labels: waiting-review

#237 fix addForm and EditForm title
  src/dashboardComponents/form/Editform.jsx
  src/dashboardComponents/form/addForm.jsx
  src/pages/admins/Classes/index.jsx
  src/pages/admins/announcements/index.jsx
  src/pages/admins/products/index.jsx
  src/pages/admins/users/index.jsx
Labels: waiting-review

#238 edit codition subscription req
  src/components/classInfo/index.jsx
  src/pages/admins/Classes/index.jsx
Labels: waiting-review

#240 update order status in dashboard and client side
  package-lock.json
  package.json
  src/components/message/index.jsx
  src/components/messageLists/index.jsx
  src/components/navbar/NavbarClient.jsx
  src/components/productDetailsCard/ProductDetails.jsx
  src/pages/admins/orders/index.jsx
Labels: waiting-review

#244 add-get calendar for classes
  package-lock.json
  package.json
  src/dashboardComponents/sidebar/index.jsx
  src/pages/admins/calendar/index.jsx
  src/pages/admins/index.js
  src/routes/router.jsx
Labels: in-progress

#246 show calendar for class
  src/components/classInfo/index.jsx
Labels: waiting-review
